### ISSUE TITLE
Readme from https://github.com/sergeychibunin/sergeychibunin as index there

### ISSUE THREAD

**Issue by aaksarin** [sergeychibunin/sergeychibunin.github.io#1]
Hi. May be you want to use readme.md from your other repo https://github.com/sergeychibunin/sergeychibunin as index in this repo.

**Comment by sergeychibunin** [comment]
Hi! Thank you for an advice. I will update my home page this way. Then I will configure a Jekyll theme in the next year :)

**Comment by sergeychibunin** [comment]
Done :)
